use crate::commands::color as c;
use clap::Args;
use std::fs;
use std::path::{Path, PathBuf};
use tracing::{error, info, warn};

#[derive(Args, Debug)]
pub struct InstallHooksArgs {
    /// Force overwrite existing hooks
    #[arg(short, long)]
    pub force: bool,

    /// Use Husky for projects with Husky installed
    #[arg(long)]
    pub husky: bool,
}

const PRE_COMMIT_HOOK: &str = r#"#!/bin/sh
# Sanctifier pre-commit hook
# Auto-generated by sanctifier install-hooks

sanctifier analyze --quiet --severity high
"#;

const PRE_PUSH_HOOK: &str = r#"#!/bin/sh
# Sanctifier pre-push hook
# Auto-generated by sanctifier install-hooks

sanctifier analyze --quiet --severity high
"#;

const HUSKY_PRE_COMMIT: &str = r#"#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

sanctifier analyze --quiet --severity high
"#;

const HUSKY_PRE_PUSH: &str = r#"#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

sanctifier analyze --quiet --severity high
"#;

pub struct HookInstaller;

impl HookInstaller {
    /// Find the .git directory by walking up from the current directory
    pub fn find_git_dir() -> anyhow::Result<PathBuf> {
        let mut current = std::env::current_dir()?;

        loop {
            let git_dir = current.join(".git");
            if git_dir.exists() && git_dir.is_dir() {
                return Ok(git_dir);
            }

            if !current.pop() {
                anyhow::bail!("Not a git repository (or any parent up to mount point)");
            }
        }
    }

    /// Check if Husky is installed in the project
    pub fn is_husky_installed() -> bool {
        let husky_dir = Path::new(".husky");
        husky_dir.exists() && husky_dir.is_dir()
    }

    /// Get the hooks directory path based on whether Husky is being used
    pub fn get_hooks_dir(use_husky: bool) -> anyhow::Result<PathBuf> {
        if use_husky {
            if !Self::is_husky_installed() {
                anyhow::bail!("Husky is not installed in this project. Run 'npx husky init' first or omit --husky flag.");
            }
            Ok(PathBuf::from(".husky"))
        } else {
            let git_dir = Self::find_git_dir()?;
            Ok(git_dir.join("hooks"))
        }
    }

    /// Check if a hook file already exists
    pub fn hook_exists(hooks_dir: &Path, hook_name: &str) -> bool {
        hooks_dir.join(hook_name).exists()
    }

    /// Write a hook file with executable permissions
    pub fn write_hook(hooks_dir: &Path, hook_name: &str, content: &str) -> anyhow::Result<PathBuf> {
        let hook_path = hooks_dir.join(hook_name);

        // Ensure hooks directory exists
        if !hooks_dir.exists() {
            fs::create_dir_all(hooks_dir)?;
        }

        // Write the hook file
        fs::write(&hook_path, content)?;

        // Make the hook executable (Unix-like systems)
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&hook_path)?.permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&hook_path, perms)?;
        }

        Ok(hook_path)
    }

    /// Install both pre-commit and pre-push hooks
    pub fn install_hooks(force: bool, use_husky: bool) -> anyhow::Result<Vec<PathBuf>> {
        let hooks_dir = Self::get_hooks_dir(use_husky)?;
        let mut installed = Vec::new();

        let hooks = if use_husky {
            vec![
                ("pre-commit", HUSKY_PRE_COMMIT),
                ("pre-push", HUSKY_PRE_PUSH),
            ]
        } else {
            vec![("pre-commit", PRE_COMMIT_HOOK), ("pre-push", PRE_PUSH_HOOK)]
        };

        for (hook_name, hook_content) in hooks {
            if Self::hook_exists(&hooks_dir, hook_name) && !force {
                warn!(
                    target: "sanctifier",
                    "Hook already exists: {}. Use --force to overwrite.",
                    hook_name
                );
                continue;
            }

            match Self::write_hook(&hooks_dir, hook_name, hook_content) {
                Ok(path) => {
                    info!(
                        target: "sanctifier",
                        "Installed {} hook",
                        hook_name
                    );
                    installed.push(path);
                }
                Err(e) => {
                    error!(
                        target: "sanctifier",
                        error = %e,
                        "Failed to install {} hook",
                        hook_name
                    );
                    return Err(e);
                }
            }
        }

        Ok(installed)
    }
}

pub struct OutputFormatter;

impl OutputFormatter {
    pub fn display_success(installed_hooks: &[PathBuf], use_husky: bool) {
        if installed_hooks.is_empty() {
            println!(
                "{} No hooks were installed (already exist, use --force to overwrite)",
                c::yellow("⚠")
            );
            return;
        }

        println!("{} Git hooks installed successfully!", c::green("✓"));

        if use_husky {
            println!("   Using Husky hooks in .husky/");
        } else {
            println!("   Using native Git hooks in .git/hooks/");
        }

        for hook in installed_hooks {
            println!("   • {}", hook.display());
        }

        println!("\n{} Sanctifier will now run automatically:", c::green("ℹ"));
        println!("   • Before each commit (pre-commit)");
        println!("   • Before each push (pre-push)");
    }

    pub fn display_error(error: &anyhow::Error) {
        error!(
            target: "sanctifier",
            error = %error,
            "Failed to install hooks"
        );
    }
}

pub fn exec(args: InstallHooksArgs) -> anyhow::Result<()> {
    // Auto-detect Husky if --husky flag is not provided
    let use_husky = args.husky || HookInstaller::is_husky_installed();

    if use_husky && !HookInstaller::is_husky_installed() {
        anyhow::bail!("Husky is not installed in this project. Run 'npx husky init' first or omit --husky flag.");
    }

    match HookInstaller::install_hooks(args.force, use_husky) {
        Ok(installed_hooks) => {
            OutputFormatter::display_success(&installed_hooks, use_husky);
            Ok(())
        }
        Err(e) => {
            OutputFormatter::display_error(&e);
            Err(e)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::test_support::CWD_LOCK;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn test_find_git_dir_in_current_directory() {
        let _guard = CWD_LOCK.lock().unwrap();
        let temp_dir = TempDir::new().unwrap();
        let git_dir = temp_dir.path().join(".git");
        fs::create_dir(&git_dir).unwrap();

        let original_dir = std::env::current_dir().unwrap();
        std::env::set_current_dir(temp_dir.path()).unwrap();

        let result = HookInstaller::find_git_dir();

        std::env::set_current_dir(original_dir).unwrap();

        assert!(result.is_ok());
        assert_eq!(
            result.unwrap().canonicalize().unwrap(),
            git_dir.canonicalize().unwrap()
        );
    }

    #[test]
    fn test_find_git_dir_in_parent_directory() {
        let _guard = CWD_LOCK.lock().unwrap();
        let temp_dir = TempDir::new().unwrap();
        let git_dir = temp_dir.path().join(".git");
        fs::create_dir(&git_dir).unwrap();

        let sub_dir = temp_dir.path().join("subdir");
        fs::create_dir(&sub_dir).unwrap();

        let original_dir = std::env::current_dir().unwrap();
        std::env::set_current_dir(&sub_dir).unwrap();

        let result = HookInstaller::find_git_dir();

        std::env::set_current_dir(original_dir).unwrap();

        assert!(result.is_ok());
        assert_eq!(
            result.unwrap().canonicalize().unwrap(),
            git_dir.canonicalize().unwrap()
        );
    }

    #[test]
    fn test_find_git_dir_not_found() {
        let _guard = CWD_LOCK.lock().unwrap();
        let temp_dir = TempDir::new().unwrap();

        let original_dir = std::env::current_dir().unwrap();
        std::env::set_current_dir(temp_dir.path()).unwrap();

        let result = HookInstaller::find_git_dir();

        std::env::set_current_dir(original_dir).unwrap();

        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("Not a git repository"));
    }

    #[test]
    fn test_hook_exists_returns_false_when_no_file() {
        let temp_dir = TempDir::new().unwrap();
        let hooks_dir = temp_dir.path();

        assert!(!HookInstaller::hook_exists(hooks_dir, "pre-commit"));
    }

    #[test]
    fn test_hook_exists_returns_true_when_file_exists() {
        let temp_dir = TempDir::new().unwrap();
        let hooks_dir = temp_dir.path();
        let hook_path = hooks_dir.join("pre-commit");

        fs::write(&hook_path, "test content").unwrap();

        assert!(HookInstaller::hook_exists(hooks_dir, "pre-commit"));
    }

    #[test]
    fn test_write_hook_creates_file() {
        let temp_dir = TempDir::new().unwrap();
        let hooks_dir = temp_dir.path().join("hooks");

        let result = HookInstaller::write_hook(&hooks_dir, "pre-commit", PRE_COMMIT_HOOK);

        assert!(result.is_ok());
        let hook_path = result.unwrap();
        assert!(hook_path.exists());
        assert_eq!(hook_path.file_name().unwrap(), "pre-commit");
    }

    #[test]
    fn test_write_hook_creates_directory_if_not_exists() {
        let temp_dir = TempDir::new().unwrap();
        let hooks_dir = temp_dir.path().join("hooks");

        assert!(!hooks_dir.exists());

        let result = HookInstaller::write_hook(&hooks_dir, "pre-commit", PRE_COMMIT_HOOK);

        assert!(result.is_ok());
        assert!(hooks_dir.exists());
    }

    #[test]
    fn test_write_hook_content_is_correct() {
        let temp_dir = TempDir::new().unwrap();
        let hooks_dir = temp_dir.path().join("hooks");

        let result = HookInstaller::write_hook(&hooks_dir, "pre-commit", PRE_COMMIT_HOOK);
        assert!(result.is_ok());

        let hook_path = result.unwrap();
        let content = fs::read_to_string(&hook_path).unwrap();
        assert_eq!(content, PRE_COMMIT_HOOK);
    }

    #[test]
    #[cfg(unix)]
    fn test_write_hook_is_executable() {
        use std::os::unix::fs::PermissionsExt;

        let temp_dir = TempDir::new().unwrap();
        let hooks_dir = temp_dir.path().join("hooks");

        let result = HookInstaller::write_hook(&hooks_dir, "pre-commit", PRE_COMMIT_HOOK);
        assert!(result.is_ok());

        let hook_path = result.unwrap();
        let metadata = fs::metadata(&hook_path).unwrap();
        let permissions = metadata.permissions();

        // Check that the file is executable (0o755 = rwxr-xr-x)
        assert_eq!(permissions.mode() & 0o111, 0o111);
    }

    #[test]
    fn test_get_hooks_dir_without_husky() {
        let _guard = CWD_LOCK.lock().unwrap();
        let temp_dir = TempDir::new().unwrap();
        let git_dir = temp_dir.path().join(".git");
        fs::create_dir(&git_dir).unwrap();

        let original_dir = std::env::current_dir().unwrap();
        std::env::set_current_dir(temp_dir.path()).unwrap();

        let result = HookInstaller::get_hooks_dir(false);

        std::env::set_current_dir(original_dir).unwrap();

        assert!(result.is_ok());
        let hooks_dir = result.unwrap();
        assert_eq!(
            hooks_dir.file_name().and_then(|n| n.to_str()),
            Some("hooks")
        );
        assert_eq!(
            hooks_dir.parent().unwrap().canonicalize().unwrap(),
            git_dir.canonicalize().unwrap()
        );
    }

    #[test]
    fn test_get_hooks_dir_with_husky() {
        let _guard = CWD_LOCK.lock().unwrap();
        let temp_dir = TempDir::new().unwrap();
        let husky_dir = temp_dir.path().join(".husky");
        fs::create_dir(&husky_dir).unwrap();

        let original_dir = std::env::current_dir().unwrap();
        std::env::set_current_dir(temp_dir.path()).unwrap();

        let result = HookInstaller::get_hooks_dir(true);

        std::env::set_current_dir(original_dir).unwrap();

        assert!(result.is_ok());
        assert_eq!(result.unwrap(), PathBuf::from(".husky"));
    }

    #[test]
    fn test_get_hooks_dir_with_husky_not_installed() {
        let _guard = CWD_LOCK.lock().unwrap();
        let temp_dir = TempDir::new().unwrap();

        let original_dir = std::env::current_dir().unwrap();
        std::env::set_current_dir(temp_dir.path()).unwrap();

        let result = HookInstaller::get_hooks_dir(true);

        std::env::set_current_dir(original_dir).unwrap();

        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("Husky is not installed"));
    }
}
